"""Worldwide market catalogue for MealDeals scrapers."""

from __future__ import annotations

from app.scrapers.hospitality_pack import merge_hospitality_into_sources

# Markets already scraped in the first worldwide pass.
SEEDED_MARKETS: list[str] = ['GB', 'US', 'CA', 'AU', 'IE', 'NZ', 'PH', 'TH', 'NL', 'BS', 'JM']

MARKET_SOURCES: dict[str, list[dict[str, str]]] = {
    'GB': [
        {"merchant": 'Tesco', "url": 'https://www.tesco.com/groceries/en-GB/promotions'},
        {"merchant": "Sainsbury's", "url": 'https://www.sainsburys.co.uk/gol-ui/promotions'},
        {"merchant": 'Pret A Manger', "url": 'https://www.pret.co.uk/en-GB/meal-deals'},
        {"merchant": 'Greggs', "url": 'https://www.greggs.co.uk/menu'},
    ],
    'US': [
        {"merchant": 'Whole Foods', "url": 'https://www.wholefoodsmarket.com/sales-flyer'},
        {"merchant": "Trader Joe's", "url": 'https://www.traderjoes.com/home/products'},
        {"merchant": 'Chipotle', "url": 'https://www.chipotle.com/'},
    ],
    'CA': [
        {"merchant": 'Loblaws', "url": 'https://www.loblaws.ca/deals'},
        {"merchant": 'Tim Hortons', "url": 'https://www.timhortons.ca/'},
        {"merchant": 'Subway', "url": 'https://www.subway.com/en-ca'},
    ],
    'AU': [
        {"merchant": 'Woolworths', "url": 'https://www.woolworths.com.au/shop/catalogue'},
        {"merchant": 'Coles', "url": 'https://www.coles.com.au/catalogues'},
        {"merchant": 'Guzman y Gomez', "url": 'https://www.guzmanygomez.com.au/'},
    ],
    'IE': [
        {"merchant": 'Dunnes Stores', "url": 'https://www.dunnesstores.com/offers'},
        {"merchant": 'Centra', "url": 'https://www.centra.ie/'},
        {"merchant": 'Supervalu', "url": 'https://shop.supervalu.ie/'},
    ],
    'NZ': [
        {"merchant": 'Countdown', "url": 'https://www.woolworths.co.nz/shop/specials'},
        {"merchant": 'New World', "url": 'https://www.newworld.co.nz/specials'},
    ],
    'PH': [
        {"merchant": 'Jollibee', "url": 'https://www.jollibee.com.ph/'},
        {"merchant": 'Mang Inasal', "url": 'https://www.manginasal.com.ph/'},
        {"merchant": 'SM Supermarket', "url": 'https://www.smsupermarket.com/'},
    ],
    'TH': [
        {"merchant": '7-Eleven Thailand', "url": 'https://www.7eleven.co.th/'},
        {"merchant": 'Big C', "url": 'https://www.bigc.co.th/'},
        {"merchant": 'Foodland', "url": 'https://www.foodland.co.th/'},
    ],
    'NL': [
        {"merchant": 'Albert Heijn', "url": 'https://www.ah.nl/bonus'},
        {"merchant": 'Jumbo', "url": 'https://www.jumbo.com/aanbiedingen'},
        {"merchant": 'HEMA', "url": 'https://www.hema.nl/'},
    ],
    'BS': [
        {"merchant": 'Super Value Bahamas', "url": 'https://www.supervaluebahamas.com/'},
        {"merchant": "Solomon's", "url": 'https://www.solomons.com/'},
    ],
    'JM': [
        {"merchant": 'Hi-Lo Food Stores', "url": 'https://www.hilofoodstores.com/'},
        {"merchant": 'Juici Patties', "url": 'https://www.juicipatties.com/'},
        {"merchant": 'Island Grill', "url": 'https://www.islandgrillja.com/'},
    ],
    'AE': [
        {"merchant": 'Carrefour UAE', "url": 'https://www.carrefouruae.com/mafuae/en/'},
        {"merchant": 'Lulu Hypermarket', "url": 'https://www.luluhypermarket.com/'},
    ],
    'AG': [
        {"merchant": 'Epicurean', "url": 'https://www.epicureanantigua.com/'},
        {"merchant": 'Food City Antigua', "url": 'https://www.foodcityantigua.com/'},
    ],
    'AR': [
        {"merchant": 'Carrefour Argentina', "url": 'https://www.carrefour.com.ar/'},
        {"merchant": 'Mostaza', "url": 'https://www.mostazaweb.com.ar/'},
    ],
    'AT': [
        {"merchant": 'Billa', "url": 'https://www.billa.at/'},
        {"merchant": 'Spar Austria', "url": 'https://www.spar.at/'},
    ],
    'BB': [
        {"merchant": 'Massey Stores', "url": 'https://www.masseystores.com/'},
        {"merchant": 'Chefette', "url": 'https://www.chefette.com/'},
    ],
    'BE': [
        {"merchant": 'Colruyt', "url": 'https://www.colruyt.be/'},
        {"merchant": 'Delhaize', "url": 'https://www.delhaize.be/'},
    ],
    'BR': [
        {"merchant": 'iFood', "url": 'https://www.ifood.com.br/'},
        {"merchant": 'Pao de Acucar', "url": 'https://www.paodeacucar.com/'},
        {"merchant": "Habib's", "url": 'https://www.habibs.com.br/'},
    ],
    'BW': [
        {"merchant": 'Choppies', "url": 'https://www.choppies.co.bw/'},
        {"merchant": 'Sefalana', "url": 'https://www.sefalana.com/'},
    ],
    'BZ': [
        {"merchant": 'Brodies', "url": 'https://www.brodiesbelize.com/'},
        {"merchant": 'James Brodie', "url": 'https://www.brodies.bz/'},
    ],
    'CH': [
        {"merchant": 'Migros', "url": 'https://www.migros.ch/'},
        {"merchant": 'Coop Switzerland', "url": 'https://www.coop.ch/'},
    ],
    'CL': [
        {"merchant": 'Lider', "url": 'https://www.lider.cl/'},
        {"merchant": 'Doggis', "url": 'https://www.doggis.cl/'},
    ],
    'CM': [
        {"merchant": 'Santa Lucia', "url": 'https://www.santalucia.cm/'},
        {"merchant": 'Casino Cameroon Supermarket', "url": 'https://www.casino.cm/'},
    ],
    'CN': [
        {"merchant": 'Hema Fresh', "url": 'https://www.freshhema.com/'},
        {"merchant": 'Meituan', "url": 'https://www.meituan.com/'},
        {"merchant": 'Luckin Coffee', "url": 'https://www.luckincoffee.com/'},
    ],
    'CO': [
        {"merchant": 'Exito', "url": 'https://www.exito.com/'},
        {"merchant": 'Presto', "url": 'https://www.presto.com.co/'},
    ],
    'CZ': [
        {"merchant": 'Albert CZ', "url": 'https://www.albert.cz/'},
        {"merchant": 'Lidl Czechia', "url": 'https://www.lidl.cz/'},
    ],
    'DE': [
        {"merchant": 'Rewe', "url": 'https://www.rewe.de/'},
        {"merchant": 'Lidl Germany', "url": 'https://www.lidl.de/'},
        {"merchant": 'Nordsee', "url": 'https://www.nordsee.com/'},
    ],
    'DK': [
        {"merchant": 'Netto', "url": 'https://www.netto.dk/'},
        {"merchant": 'Rema 1000', "url": 'https://www.rema1000.dk/'},
    ],
    'EG': [
        {"merchant": 'Carrefour Egypt', "url": 'https://www.carrefouregypt.com/'},
        {"merchant": 'Spinneys Egypt', "url": 'https://www.spinneys.com.eg/'},
    ],
    'ES': [
        {"merchant": 'Mercadona', "url": 'https://www.mercadona.es/'},
        {"merchant": 'El Corte Ingles', "url": 'https://www.elcorteingles.es/'},
    ],
    'FI': [
        {"merchant": 'K-Market', "url": 'https://www.k-ruoka.fi/'},
        {"merchant": 'Prisma', "url": 'https://www.prisma.fi/'},
    ],
    'FJ': [
        {"merchant": 'MH Supermarket', "url": 'https://www.mhinternational.com.fj/'},
        {"merchant": 'New World Fiji', "url": 'https://www.newworld.com.fj/'},
    ],
    'FM': [
        {"merchant": 'Pohnpei Ace', "url": 'https://www.pohnpeiace.fm/'},
        {"merchant": 'A&E Market', "url": 'https://www.aemarket.fm/'},
    ],
    'FR': [
        {"merchant": 'Carrefour', "url": 'https://www.carrefour.fr/'},
        {"merchant": 'Monoprix', "url": 'https://www.monoprix.fr/'},
        {"merchant": 'Paul Bakery', "url": 'https://www.paul.fr/'},
    ],
    'GD': [
        {"merchant": 'Real Value Supermarket', "url": 'https://www.realvaluegd.com/'},
        {"merchant": 'Foodland Grenada', "url": 'https://www.foodlandgrenada.com/'},
    ],
    'GH': [
        {"merchant": 'Melcom', "url": 'https://www.melcom.com.gh/'},
        {"merchant": 'Papaye', "url": 'https://www.papaye.com.gh/'},
        {"merchant": 'KFC Ghana', "url": 'https://www.kfc.com.gh/'},
    ],
    'GM': [
        {"merchant": 'Kairaba Shopping', "url": 'https://www.kairabashopping.com/'},
        {"merchant": 'Supersaver Gambia', "url": 'https://www.supersaver.gm/'},
    ],
    'GR': [
        {"merchant": 'Sklavenitis', "url": 'https://www.sklavenitis.gr/'},
        {"merchant": 'AB Vassilopoulos', "url": 'https://www.ab.gr/'},
    ],
    'GY': [
        {"merchant": 'Massy Guyana', "url": 'https://www.massygroup.com/'},
        {"merchant": 'Demico House', "url": 'https://www.demicohouse.com/'},
    ],
    'HR': [
        {"merchant": 'Konzum', "url": 'https://www.konzum.hr/'},
        {"merchant": 'Spar Croatia', "url": 'https://www.spar.hr/'},
    ],
    'ID': [
        {"merchant": 'Indomaret', "url": 'https://www.indomaret.co.id/'},
        {"merchant": 'Alfamart', "url": 'https://www.alfamart.co.id/'},
        {"merchant": 'HokBen', "url": 'https://www.hokben.co.id/'},
    ],
    'IL': [
        {"merchant": 'Shufersal', "url": 'https://www.shufersal.co.il/'},
        {"merchant": 'Rami Levy', "url": 'https://www.rami-levy.co.il/'},
    ],
    'IN': [
        {"merchant": 'JioMart', "url": 'https://www.jiomart.com/'},
        {"merchant": 'Swiggy', "url": 'https://www.swiggy.com/'},
        {"merchant": "Domino's India", "url": 'https://www.dominos.co.in/'},
    ],
    'IS': [
        {"merchant": 'Bonus', "url": 'https://www.bonus.is/'},
        {"merchant": 'Kronan', "url": 'https://www.kronan.is/'},
    ],
    'IT': [
        {"merchant": 'Esselunga', "url": 'https://www.esselunga.it/'},
        {"merchant": 'Autogrill', "url": 'https://www.autogrill.it/'},
    ],
    'JO': [
        {"merchant": 'Carrefour Jordan', "url": 'https://www.carrefour.jo/'},
        {"merchant": 'Safeway Jordan', "url": 'https://www.safeway.jo/'},
    ],
    'JP': [
        {"merchant": '7-Eleven Japan', "url": 'https://www.sej.co.jp/'},
        {"merchant": 'Lawson', "url": 'https://www.lawson.co.jp/'},
        {"merchant": 'FamilyMart', "url": 'https://www.family.co.jp/'},
    ],
    'KE': [
        {"merchant": 'Naivas', "url": 'https://naivas.online/'},
        {"merchant": 'Java House', "url": 'https://www.javahouseafrica.com/'},
        {"merchant": 'KFC Kenya', "url": 'https://www.kfc.co.ke/'},
    ],
    'KI': [
        {"merchant": 'Betio Market', "url": 'https://www.betiomarket.ki/'},
        {"merchant": 'Bairiki Stores', "url": 'https://www.bairikistores.ki/'},
    ],
    'KN': [
        {"merchant": "Ram's Supermarket", "url": 'https://www.ramssupermarket.com/'},
        {"merchant": 'Ballahoo', "url": 'https://www.ballahoo.com/'},
    ],
    'KR': [
        {"merchant": 'CU Convenience', "url": 'https://www.bgfretail.com/'},
        {"merchant": 'GS25', "url": 'https://www.gsretail.com/'},
        {"merchant": 'Emart', "url": 'https://www.emart.com/'},
    ],
    'LR': [
        {"merchant": 'Stop & Shop Liberia', "url": 'https://www.stopandshopliberia.com/'},
        {"merchant": 'Exclusive Supermarket', "url": 'https://www.exclusiveliberia.com/'},
    ],
    'LS': [
        {"merchant": 'Shoprite Lesotho', "url": 'https://www.shoprite.co.ls/'},
        {"merchant": 'Pick n Pay LS', "url": 'https://www.pnp.co.ls/'},
    ],
    'MA': [
        {"merchant": 'Marjane', "url": 'https://www.marjane.ma/'},
        {"merchant": 'Carrefour Morocco', "url": 'https://www.carrefour.ma/'},
    ],
    'MH': [
        {"merchant": 'Formosa Market', "url": 'https://www.formosamarket.mh/'},
        {"merchant": 'K&K Supermarket', "url": 'https://www.kksupermarket.mh/'},
    ],
    'MT': [
        {"merchant": 'Pavi Supermarket', "url": 'https://www.pavi.com.mt/'},
        {"merchant": 'Scotts Supermarket', "url": 'https://www.scotts.com.mt/'},
    ],
    'MW': [
        {"merchant": 'Shoprite Malawi', "url": 'https://www.shoprite.co.mw/'},
        {"merchant": 'Peoples Trading', "url": 'https://www.peoplesmalawi.com/'},
    ],
    'MX': [
        {"merchant": 'OXXO', "url": 'https://www.oxxo.com/'},
        {"merchant": 'Walmart Mexico', "url": 'https://www.walmart.com.mx/'},
        {"merchant": 'Vips', "url": 'https://www.vips.com.mx/'},
    ],
    'MY': [
        {"merchant": '99 Speedmart', "url": 'https://www.99speedmart.com.my/'},
        {"merchant": 'Secret Recipe', "url": 'https://www.secretrecipe.com.my/'},
    ],
    'NA': [
        {"merchant": 'Shoprite Namibia', "url": 'https://www.shoprite.com.na/'},
        {"merchant": 'Checkers Namibia', "url": 'https://www.checkers.com.na/'},
    ],
    'NG': [
        {"merchant": 'Shoprite Nigeria', "url": 'https://www.shoprite.com.ng/'},
        {"merchant": 'Chicken Republic', "url": 'https://www.chicken-republic.com/'},
        {"merchant": "Mr Bigg's", "url": 'https://www.mrbiggs.com/'},
    ],
    'NO': [
        {"merchant": 'Rema 1000 NO', "url": 'https://www.rema.no/'},
        {"merchant": 'Meny', "url": 'https://www.meny.no/'},
    ],
    'NR': [
        {"merchant": 'Capelle & Partner', "url": 'https://www.capelle.com.nr/'},
        {"merchant": 'Nauru Superstore', "url": 'https://www.naurusuperstore.nr/'},
    ],
    'PG': [
        {"merchant": 'Stop N Shop PNG', "url": 'https://www.stopnshop.com.pg/'},
        {"merchant": 'RH Hypermarket', "url": 'https://www.rhtrading.com.pg/'},
    ],
    'PK': [
        {"merchant": 'Imtiaz Super Market', "url": 'https://www.imtiaz.com.pk/'},
        {"merchant": 'Foodpanda Pakistan', "url": 'https://www.foodpanda.pk/'},
    ],
    'PL': [
        {"merchant": 'Biedronka', "url": 'https://www.biedronka.pl/'},
        {"merchant": 'Zabka', "url": 'https://www.zabka.pl/'},
    ],
    'PT': [
        {"merchant": 'Continente', "url": 'https://www.continente.pt/'},
        {"merchant": 'Pingo Doce', "url": 'https://www.pingodoce.pt/'},
    ],
    'PW': [
        {"merchant": "Surangel's", "url": 'https://www.surangels.com/'},
        {"merchant": 'WCTC Shopping', "url": 'https://www.wctc.com.pw/'},
    ],
    'QA': [
        {"merchant": 'Lulu Qatar', "url": 'https://www.luluhypermarket.com/en-qa'},
        {"merchant": 'Carrefour Qatar', "url": 'https://www.carrefourqatar.com/'},
    ],
    'RW': [
        {"merchant": 'Simba Supermarket', "url": 'https://www.simbasupermarket.rw/'},
        {"merchant": 'Bourbon Coffee', "url": 'https://www.bourboncoffee.rw/'},
    ],
    'SB': [
        {"merchant": 'Honiara Central Market', "url": 'https://www.honiaramarket.com/'},
        {"merchant": 'Island Enterprises', "url": 'https://www.islandenterprises.com.sb/'},
    ],
    'SE': [
        {"merchant": 'ICA', "url": 'https://www.ica.se/'},
        {"merchant": 'Pressbyran', "url": 'https://www.pressbyran.se/'},
    ],
    'SG': [
        {"merchant": 'FairPrice', "url": 'https://www.fairprice.com.sg/promotions'},
        {"merchant": 'Hawker Centre Deals', "url": 'https://www.visitsingapore.com/'},
        {"merchant": 'Toast Box', "url": 'https://www.toastbox.com.sg/'},
    ],
    'SI': [
        {"merchant": 'Mercator', "url": 'https://www.mercator.si/'},
        {"merchant": 'Spar Slovenia', "url": 'https://www.spar.si/'},
    ],
    'SK': [
        {"merchant": 'Tesco Slovakia', "url": 'https://www.tesco.sk/'},
        {"merchant": 'Billa Slovakia', "url": 'https://www.billa.sk/'},
    ],
    'SL': [
        {"merchant": 'Choithrams SL', "url": 'https://www.choithramssl.com/'},
        {"merchant": 'Supermarket SL', "url": 'https://www.supermarket.sl/'},
    ],
    'SS': [
        {"merchant": 'Juba Market', "url": 'https://www.jubamarket.com/'},
        {"merchant": 'Konyo Konyo', "url": 'https://www.konyokonyo.com/'},
    ],
    'SZ': [
        {"merchant": 'Shoprite Eswatini', "url": 'https://www.shoprite.co.sz/'},
        {"merchant": 'Spar Eswatini', "url": 'https://www.spar.co.sz/'},
    ],
    'TN': [
        {"merchant": 'Carrefour Tunisia', "url": 'https://www.carrefour.tn/'},
        {"merchant": 'Monoprix Tunisia', "url": 'https://www.monoprix.tn/'},
    ],
    'TO': [
        {"merchant": 'Friendly Islands Market', "url": 'https://www.friendlyislands.to/'},
        {"merchant": 'Tonga Co-op', "url": 'https://www.tongacoop.to/'},
    ],
    'TR': [
        {"merchant": 'Migros Turkey', "url": 'https://www.migros.com.tr/'},
        {"merchant": 'A101', "url": 'https://www.a101.com.tr/'},
    ],
    'TT': [
        {"merchant": 'Massy Stores TT', "url": 'https://www.massystorestt.com/'},
        {"merchant": 'Rituals Coffee', "url": 'https://www.ritualscoffee.com/'},
    ],
    'TV': [
        {"merchant": 'Funafuti Market', "url": 'https://www.funafutimarket.tv/'},
        {"merchant": 'Tuvalu Cooperative', "url": 'https://www.tuvalu.coop/'},
    ],
    'UG': [
        {"merchant": 'Shoprite Uganda', "url": 'https://www.shoprite.co.ug/'},
        {"merchant": 'Cafe Javas', "url": 'https://www.cafejavas.co.ug/'},
    ],
    'VC': [
        {"merchant": 'Massy SVG', "url": 'https://www.massygroup.com/'},
        {"merchant": 'C.K. Greaves', "url": 'https://www.ckgreaves.com/'},
    ],
    'VN': [
        {"merchant": 'VinMart', "url": 'https://www.vinmart.com/'},
        {"merchant": 'Highlands Coffee', "url": 'https://www.highlandscoffee.com.vn/'},
    ],
    'VU': [
        {"merchant": 'Au Bon Marche', "url": 'https://www.aubonmarche.vu/'},
        {"merchant": 'Centerpoint Vanuatu', "url": 'https://www.centerpoint.vu/'},
    ],
    'WS': [
        {"merchant": 'Farmers Samoa', "url": 'https://www.farmers.ws/'},
        {"merchant": 'Ah Liki Wholesale', "url": 'https://www.ahliki.ws/'},
    ],
    'ZA': [
        {"merchant": 'Checkers', "url": 'https://www.checkers.co.za/specials'},
        {"merchant": 'Woolworths SA', "url": 'https://www.woolworths.co.za/'},
        {"merchant": "Nando's", "url": 'https://www.nandos.co.za/'},
    ],
    'ZM': [
        {"merchant": 'Shoprite Zambia', "url": 'https://www.shoprite.co.zm/'},
        {"merchant": 'Hungry Lion', "url": 'https://www.hungrylion.co.zm/'},
    ],
    'ZW': [
        {"merchant": 'OK Zimbabwe', "url": 'https://www.okz.co.zw/'},
        {"merchant": 'Chicken Inn', "url": 'https://www.chickeninn.co.zw/'},
    ],
}

MARKET_CITIES: dict[str, list[str]] = {
    'GB': ['London', 'Manchester', 'Birmingham', 'Leeds', 'Glasgow', 'Edinburgh', 'Liverpool', 'Bristol', 'Sheffield', 'Newcastle', 'Cardiff', 'Belfast', 'Nottingham', 'Leicester', 'Brighton', 'Southampton', 'Coventry', 'Reading', 'Cambridge', 'Oxford', 'Aberdeen', 'Plymouth', 'Swansea', 'York', 'Bath'],
    'US': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Jacksonville', 'San Francisco', 'Seattle', 'Denver', 'Boston', 'Nashville', 'Detroit', 'Portland', 'Las Vegas', 'Miami', 'Atlanta', 'Washington', 'Minneapolis', 'Charlotte', 'Tampa', 'Orlando', 'Cleveland', 'Pittsburgh', 'Kansas City', 'St Louis', 'Sacramento', 'Salt Lake City', 'Honolulu', 'New Orleans', 'Raleigh', 'Columbus', 'Indianapolis', 'Cincinnati', 'Milwaukee'],
    'CA': ['Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Ottawa', 'Edmonton', 'Winnipeg', 'Quebec City', 'Hamilton', 'Halifax', 'Victoria', 'Saskatoon', 'Regina', 'London', 'Kitchener', 'Mississauga', 'Brampton', 'Surrey'],
    'IE': ['Dublin', 'Cork', 'Galway', 'Limerick', 'Waterford', 'Kilkenny', 'Sligo', 'Drogheda', 'Dundalk', 'Wexford'],
    'AU': ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Canberra', 'Hobart', 'Gold Coast', 'Newcastle', 'Wollongong', 'Geelong', 'Cairns', 'Darwin', 'Townsville', 'Sunshine Coast'],
    'NZ': ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga', 'Dunedin', 'Queenstown', 'Palmerston North', 'Napier', 'Nelson'],
    'PH': ['Manila', 'Quezon City', 'Cebu', 'Davao', 'Makati', 'Pasig', 'Taguig', 'Iloilo', 'Cagayan De Oro', 'Bacolod', 'Baguio', 'Angeles'],
    'TH': ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Chiang Rai', 'Hat Yai', 'Khon Kaen', 'Hua Hin', 'Krabi', 'Udon Thani'],
    'NL': ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Groningen', 'Maastricht', 'Haarlem', 'Tilburg', 'Leiden'],
    'BS': ['Nassau', 'Freeport', 'Marsh Harbour'],
    'JM': ['Kingston', 'Montego Bay', 'Ocho Rios', 'Spanish Town', 'Negril'],
    'AE': ['Dubai', 'Abu Dhabi', 'Sharjah'],
    'AG': ['St Johns'],
    'AR': ['Buenos Aires', 'Cordoba', 'Mendoza', 'Rosario'],
    'AT': ['Vienna', 'Salzburg', 'Innsbruck'],
    'BB': ['Bridgetown', 'Speightstown'],
    'BE': ['Brussels', 'Antwerp', 'Ghent'],
    'BR': ['Sao Paulo', 'Rio De Janeiro', 'Brasilia', 'Salvador', 'Belo Horizonte'],
    'BW': ['Gaborone', 'Francistown'],
    'BZ': ['Belize City', 'Belmopan', 'San Ignacio'],
    'CH': ['Zurich', 'Geneva', 'Bern'],
    'CL': ['Santiago', 'Valparaiso', 'Concepcion'],
    'CM': ['Douala', 'Yaounde'],
    'CN': ['Shanghai', 'Beijing', 'Guangzhou', 'Shenzhen', 'Chengdu'],
    'CO': ['Bogota', 'Medellin', 'Cali', 'Cartagena'],
    'CZ': ['Prague', 'Brno', 'Ostrava'],
    'DE': ['Berlin', 'Munich', 'Hamburg', 'Cologne', 'Frankfurt'],
    'DK': ['Copenhagen', 'Aarhus', 'Odense'],
    'EG': ['Cairo', 'Alexandria', 'Giza'],
    'ES': ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Bilbao'],
    'FI': ['Helsinki', 'Tampere', 'Turku'],
    'FJ': ['Suva', 'Nadi', 'Lautoka'],
    'FM': ['Palikir', 'Kolonia'],
    'FR': ['Paris', 'Lyon', 'Marseille', 'Nice', 'Bordeaux'],
    'GD': ['St Georges'],
    'GH': ['Accra', 'Kumasi', 'Tamale'],
    'GM': ['Banjul', 'Serekunda'],
    'GR': ['Athens', 'Thessaloniki', 'Heraklion'],
    'GY': ['Georgetown', 'Linden'],
    'HR': ['Zagreb', 'Split', 'Dubrovnik'],
    'ID': ['Jakarta', 'Surabaya', 'Bandung', 'Bali', 'Medan'],
    'IL': ['Tel Aviv', 'Jerusalem', 'Haifa'],
    'IN': ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata', 'Pune'],
    'IS': ['Reykjavik', 'Akureyri'],
    'IT': ['Rome', 'Milan', 'Naples', 'Florence', 'Turin'],
    'JO': ['Amman', 'Irbid', 'Aqaba'],
    'JP': ['Tokyo', 'Osaka', 'Kyoto', 'Yokohama', 'Nagoya'],
    'KE': ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru'],
    'KI': ['Tarawa'],
    'KN': ['Basseterre'],
    'KR': ['Seoul', 'Busan', 'Incheon', 'Daegu'],
    'LR': ['Monrovia'],
    'LS': ['Maseru'],
    'MA': ['Casablanca', 'Rabat', 'Marrakesh', 'Tangier'],
    'MH': ['Majuro'],
    'MT': ['Valletta', 'Sliema', 'St Julians'],
    'MW': ['Lilongwe', 'Blantyre'],
    'MX': ['Mexico City', 'Guadalajara', 'Monterrey', 'Cancun', 'Tijuana'],
    'MY': ['Kuala Lumpur', 'Penang', 'Johor Bahru', 'Kota Kinabalu'],
    'NA': ['Windhoek', 'Swakopmund'],
    'NG': ['Lagos', 'Abuja', 'Port Harcourt', 'Ibadan', 'Kano'],
    'NO': ['Oslo', 'Bergen', 'Trondheim'],
    'NR': ['Yaren'],
    'PG': ['Port Moresby', 'Lae'],
    'PK': ['Karachi', 'Lahore', 'Islamabad', 'Rawalpindi'],
    'PL': ['Warsaw', 'Krakow', 'Gdansk', 'Wroclaw'],
    'PT': ['Lisbon', 'Porto', 'Faro'],
    'PW': ['Ngerulmud', 'Koror'],
    'QA': ['Doha', 'Al Rayyan'],
    'RW': ['Kigali', 'Butare'],
    'SB': ['Honiara'],
    'SE': ['Stockholm', 'Gothenburg', 'Malmo'],
    'SG': ['Singapore'],
    'SI': ['Ljubljana', 'Maribor'],
    'SK': ['Bratislava', 'Kosice'],
    'SL': ['Freetown'],
    'SS': ['Juba'],
    'SZ': ['Mbabane', 'Manzini'],
    'TN': ['Tunis', 'Sfax', 'Sousse'],
    'TO': ['Nukualofa'],
    'TR': ['Istanbul', 'Ankara', 'Izmir', 'Antalya'],
    'TT': ['Port Of Spain', 'San Fernando', 'Chaguanas'],
    'TV': ['Funafuti'],
    'UG': ['Kampala', 'Entebbe', 'Jinja'],
    'VC': ['Kingstown'],
    'VN': ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Nha Trang'],
    'VU': ['Port Vila'],
    'WS': ['Apia'],
    'ZA': ['Cape Town', 'Johannesburg', 'Durban', 'Pretoria', 'Port Elizabeth'],
    'ZM': ['Lusaka', 'Ndola', 'Kitwe'],
    'ZW': ['Harare', 'Bulawayo'],
}

DEFAULT_CURRENCY: dict[str, str] = {
    'GB': 'GBP',
    'US': 'USD',
    'CA': 'CAD',
    'AU': 'AUD',
    'IE': 'EUR',
    'NZ': 'NZD',
    'PH': 'PHP',
    'TH': 'THB',
    'NL': 'EUR',
    'BS': 'BSD',
    'JM': 'JMD',
    'AE': 'AED',
    'AG': 'XCD',
    'AR': 'ARS',
    'AT': 'EUR',
    'BB': 'BBD',
    'BE': 'EUR',
    'BR': 'BRL',
    'BW': 'BWP',
    'BZ': 'BZD',
    'CH': 'CHF',
    'CL': 'CLP',
    'CM': 'XAF',
    'CN': 'CNY',
    'CO': 'COP',
    'CZ': 'CZK',
    'DE': 'EUR',
    'DK': 'DKK',
    'EG': 'EGP',
    'ES': 'EUR',
    'FI': 'EUR',
    'FJ': 'FJD',
    'FM': 'USD',
    'FR': 'EUR',
    'GD': 'XCD',
    'GH': 'GHS',
    'GM': 'GMD',
    'GR': 'EUR',
    'GY': 'GYD',
    'HR': 'EUR',
    'ID': 'IDR',
    'IL': 'ILS',
    'IN': 'INR',
    'IS': 'ISK',
    'IT': 'EUR',
    'JO': 'JOD',
    'JP': 'JPY',
    'KE': 'KES',
    'KI': 'AUD',
    'KN': 'XCD',
    'KR': 'KRW',
    'LR': 'LRD',
    'LS': 'LSL',
    'MA': 'MAD',
    'MH': 'USD',
    'MT': 'EUR',
    'MW': 'MWK',
    'MX': 'MXN',
    'MY': 'MYR',
    'NA': 'NAD',
    'NG': 'NGN',
    'NO': 'NOK',
    'NR': 'AUD',
    'PG': 'PGK',
    'PK': 'PKR',
    'PL': 'PLN',
    'PT': 'EUR',
    'PW': 'USD',
    'QA': 'QAR',
    'RW': 'RWF',
    'SB': 'SBD',
    'SE': 'SEK',
    'SG': 'SGD',
    'SI': 'EUR',
    'SK': 'EUR',
    'SL': 'SLE',
    'SS': 'SSP',
    'SZ': 'SZL',
    'TN': 'TND',
    'TO': 'TOP',
    'TR': 'TRY',
    'TT': 'TTD',
    'TV': 'AUD',
    'UG': 'UGX',
    'VC': 'XCD',
    'VN': 'VND',
    'VU': 'VUV',
    'WS': 'WST',
    'ZA': 'ZAR',
    'ZM': 'ZMW',
    'ZW': 'USD',
}

CURRENCY_RATES: dict[str, tuple[str, str]] = {
    'USD': ('1.000000', '$'),
    'GBP': ('0.790000', '£'),
    'EUR': ('0.920000', '€'),
    'CAD': ('1.360000', 'C$'),
    'AUD': ('1.520000', 'A$'),
    'NZD': ('1.650000', 'NZ$'),
    'SGD': ('1.340000', 'S$'),
    'ZAR': ('18.500000', 'R'),
    'PHP': ('56.000000', '₱'),
    'THB': ('35.000000', '฿'),
    'BSD': ('1.000000', 'B$'),
    'JMD': ('155.000000', 'J$'),
    'INR': ('83.000000', '₹'),
    'AED': ('3.672500', 'د.إ'),
    'XCD': ('2.700000', 'EC$'),
    'ARS': ('950.000000', '$'),
    'BBD': ('2.000000', 'Bds$'),
    'BRL': ('5.500000', 'R$'),
    'BWP': ('13.500000', 'P'),
    'BZD': ('2.000000', 'BZ$'),
    'CHF': ('0.880000', 'CHF'),
    'CLP': ('950.000000', '$'),
    'XAF': ('600.000000', 'FCFA'),
    'CNY': ('7.250000', '¥'),
    'COP': ('4100.000000', '$'),
    'CZK': ('23.000000', 'Kč'),
    'DKK': ('6.900000', 'kr'),
    'EGP': ('48.000000', 'E£'),
    'FJD': ('2.250000', 'FJ$'),
    'GHS': ('15.500000', 'GH₵'),
    'GMD': ('67.000000', 'D'),
    'GYD': ('209.000000', 'G$'),
    'IDR': ('16000.000000', 'Rp'),
    'ILS': ('3.700000', '₪'),
    'ISK': ('138.000000', 'kr'),
    'JOD': ('0.710000', 'د.ا'),
    'JPY': ('150.000000', '¥'),
    'KES': ('130.000000', 'KSh'),
    'KRW': ('1350.000000', '₩'),
    'LRD': ('190.000000', 'L$'),
    'LSL': ('18.500000', 'L'),
    'MAD': ('10.000000', 'د.م.'),
    'MWK': ('1730.000000', 'MK'),
    'MXN': ('17.200000', 'MX$'),
    'MYR': ('4.700000', 'RM'),
    'NAD': ('18.500000', 'N$'),
    'NGN': ('1550.000000', '₦'),
    'NOK': ('10.800000', 'kr'),
    'PGK': ('3.900000', 'K'),
    'PKR': ('278.000000', '₨'),
    'PLN': ('4.000000', 'zł'),
    'QAR': ('3.640000', 'ر.ق'),
    'RWF': ('1300.000000', 'FRw'),
    'SBD': ('8.400000', 'SI$'),
    'SEK': ('10.500000', 'kr'),
    'SLE': ('22.500000', 'Le'),
    'SSP': ('1300.000000', 'SSP'),
    'SZL': ('18.500000', 'E'),
    'TND': ('3.100000', 'د.ت'),
    'TOP': ('2.350000', 'T$'),
    'TRY': ('34.000000', '₺'),
    'TTD': ('6.800000', 'TT$'),
    'UGX': ('3700.000000', 'USh'),
    'VND': ('25000.000000', '₫'),
    'VUV': ('120.000000', 'VT'),
    'WST': ('2.750000', 'T'),
    'ZMW': ('27.000000', 'ZK'),
}

CITY_COORDS: dict[tuple[str, str], tuple[float, float]] = {
    ('AE', 'Dubai'): (25.2048, 55.2708),
    ('AE', 'Abu Dhabi'): (24.4539, 54.3773),
    ('AE', 'Sharjah'): (25.3463, 55.4209),
    ('AG', 'St Johns'): (17.1274, -61.8468),
    ('AR', 'Buenos Aires'): (-34.6037, -58.3816),
    ('AR', 'Cordoba'): (-31.4201, -64.1888),
    ('AR', 'Mendoza'): (-32.8895, -68.8458),
    ('AR', 'Rosario'): (-32.9442, -60.6505),
    ('AT', 'Vienna'): (48.2082, 16.3738),
    ('AT', 'Salzburg'): (47.8095, 13.055),
    ('AT', 'Innsbruck'): (47.2692, 11.4041),
    ('BB', 'Bridgetown'): (13.0975, -59.6145),
    ('BB', 'Speightstown'): (13.25, -59.65),
    ('BE', 'Brussels'): (50.8503, 4.3517),
    ('BE', 'Antwerp'): (51.2194, 4.4025),
    ('BE', 'Ghent'): (51.0543, 3.7174),
    ('BR', 'Sao Paulo'): (-23.5505, -46.6333),
    ('BR', 'Rio De Janeiro'): (-22.9068, -43.1729),
    ('BR', 'Brasilia'): (-15.8267, -47.9218),
    ('BR', 'Salvador'): (-12.9777, -38.5016),
    ('BR', 'Belo Horizonte'): (-19.9167, -43.9345),
    ('BW', 'Gaborone'): (-24.6282, 25.9231),
    ('BW', 'Francistown'): (-21.1702, 27.5079),
    ('BZ', 'Belize City'): (17.5046, -88.1962),
    ('BZ', 'Belmopan'): (17.2514, -88.759),
    ('BZ', 'San Ignacio'): (17.1588, -89.0696),
    ('CH', 'Zurich'): (47.3769, 8.5417),
    ('CH', 'Geneva'): (46.2044, 6.1432),
    ('CH', 'Bern'): (46.948, 7.4474),
    ('CL', 'Santiago'): (-33.4489, -70.6693),
    ('CL', 'Valparaiso'): (-33.0472, -71.6127),
    ('CL', 'Concepcion'): (-36.8201, -73.0444),
    ('CM', 'Douala'): (4.0511, 9.7679),
    ('CM', 'Yaounde'): (3.848, 11.5021),
    ('CN', 'Shanghai'): (31.2304, 121.4737),
    ('CN', 'Beijing'): (39.9042, 116.4074),
    ('CN', 'Guangzhou'): (23.1291, 113.2644),
    ('CN', 'Shenzhen'): (22.5431, 114.0579),
    ('CN', 'Chengdu'): (30.5728, 104.0668),
    ('CO', 'Bogota'): (4.711, -74.0721),
    ('CO', 'Medellin'): (6.2476, -75.5658),
    ('CO', 'Cali'): (3.4516, -76.532),
    ('CO', 'Cartagena'): (10.391, -75.4794),
    ('CZ', 'Prague'): (50.0755, 14.4378),
    ('CZ', 'Brno'): (49.1951, 16.6068),
    ('CZ', 'Ostrava'): (49.8209, 18.2625),
    ('DE', 'Berlin'): (52.52, 13.405),
    ('DE', 'Munich'): (48.1351, 11.582),
    ('DE', 'Hamburg'): (53.5511, 9.9937),
    ('DE', 'Cologne'): (50.9375, 6.9603),
    ('DE', 'Frankfurt'): (50.1109, 8.6821),
    ('DK', 'Copenhagen'): (55.6761, 12.5683),
    ('DK', 'Aarhus'): (56.1629, 10.2039),
    ('DK', 'Odense'): (55.4038, 10.4024),
    ('EG', 'Cairo'): (30.0444, 31.2357),
    ('EG', 'Alexandria'): (31.2001, 29.9187),
    ('EG', 'Giza'): (30.0131, 31.2089),
    ('ES', 'Madrid'): (40.4168, -3.7038),
    ('ES', 'Barcelona'): (41.3874, 2.1686),
    ('ES', 'Valencia'): (39.4699, -0.3763),
    ('ES', 'Seville'): (37.3891, -5.9845),
    ('ES', 'Bilbao'): (43.263, -2.935),
    ('FI', 'Helsinki'): (60.1699, 24.9384),
    ('FI', 'Tampere'): (61.4978, 23.761),
    ('FI', 'Turku'): (60.4518, 22.2666),
    ('FJ', 'Suva'): (-18.1416, 178.4419),
    ('FJ', 'Nadi'): (-17.7765, 177.4356),
    ('FJ', 'Lautoka'): (-17.6167, 177.45),
    ('FM', 'Palikir'): (6.9248, 158.161),
    ('FM', 'Kolonia'): (6.964, 158.208),
    ('FR', 'Paris'): (48.8566, 2.3522),
    ('FR', 'Lyon'): (45.764, 4.8357),
    ('FR', 'Marseille'): (43.2965, 5.3698),
    ('FR', 'Nice'): (43.7102, 7.262),
    ('FR', 'Bordeaux'): (44.8378, -0.5792),
    ('GD', 'St Georges'): (12.056, -61.7486),
    ('GH', 'Accra'): (5.6037, -0.187),
    ('GH', 'Kumasi'): (6.6885, -1.6244),
    ('GH', 'Tamale'): (9.4008, -0.8393),
    ('GM', 'Banjul'): (13.4549, -16.579),
    ('GM', 'Serekunda'): (13.438, -16.678),
    ('GR', 'Athens'): (37.9838, 23.7275),
    ('GR', 'Thessaloniki'): (40.6401, 22.9444),
    ('GR', 'Heraklion'): (35.3387, 25.1442),
    ('GY', 'Georgetown'): (6.8013, -58.1551),
    ('GY', 'Linden'): (6.0, -58.3),
    ('HR', 'Zagreb'): (45.815, 15.9819),
    ('HR', 'Split'): (43.5081, 16.4402),
    ('HR', 'Dubrovnik'): (42.6507, 18.0944),
    ('ID', 'Jakarta'): (-6.2088, 106.8456),
    ('ID', 'Surabaya'): (-7.2575, 112.7521),
    ('ID', 'Bandung'): (-6.9175, 107.6191),
    ('ID', 'Bali'): (-8.4095, 115.1889),
    ('ID', 'Medan'): (3.5952, 98.6722),
    ('IL', 'Tel Aviv'): (32.0853, 34.7818),
    ('IL', 'Jerusalem'): (31.7683, 35.2137),
    ('IL', 'Haifa'): (32.794, 34.9896),
    ('IN', 'Mumbai'): (19.076, 72.8777),
    ('IN', 'Delhi'): (28.6139, 77.209),
    ('IN', 'Bangalore'): (12.9716, 77.5946),
    ('IN', 'Hyderabad'): (17.385, 78.4867),
    ('IN', 'Chennai'): (13.0827, 80.2707),
    ('IN', 'Kolkata'): (22.5726, 88.3639),
    ('IN', 'Pune'): (18.5204, 73.8567),
    ('IS', 'Reykjavik'): (64.1466, -21.9426),
    ('IS', 'Akureyri'): (65.6835, -18.1262),
    ('IT', 'Rome'): (41.9028, 12.4964),
    ('IT', 'Milan'): (45.4642, 9.19),
    ('IT', 'Naples'): (40.8518, 14.2681),
    ('IT', 'Florence'): (43.7696, 11.2558),
    ('IT', 'Turin'): (45.0703, 7.6869),
    ('JO', 'Amman'): (31.9454, 35.9284),
    ('JO', 'Irbid'): (32.5556, 35.85),
    ('JO', 'Aqaba'): (29.532, 35.0063),
    ('JP', 'Tokyo'): (35.6762, 139.6503),
    ('JP', 'Osaka'): (34.6937, 135.5023),
    ('JP', 'Kyoto'): (35.0116, 135.7681),
    ('JP', 'Yokohama'): (35.4437, 139.638),
    ('JP', 'Nagoya'): (35.1815, 136.9066),
    ('KE', 'Nairobi'): (-1.2921, 36.8219),
    ('KE', 'Mombasa'): (-4.0435, 39.6682),
    ('KE', 'Kisumu'): (-0.0917, 34.768),
    ('KE', 'Nakuru'): (-0.3031, 36.08),
    ('KI', 'Tarawa'): (1.4518, 172.9717),
    ('KN', 'Basseterre'): (17.3026, -62.7177),
    ('KR', 'Seoul'): (37.5665, 126.978),
    ('KR', 'Busan'): (35.1796, 129.0756),
    ('KR', 'Incheon'): (37.4563, 126.7052),
    ('KR', 'Daegu'): (35.8714, 128.6014),
    ('LR', 'Monrovia'): (6.3156, -10.8074),
    ('LS', 'Maseru'): (-29.31, 27.48),
    ('MA', 'Casablanca'): (33.5731, -7.5898),
    ('MA', 'Rabat'): (34.0209, -6.8416),
    ('MA', 'Marrakesh'): (31.6295, -7.9811),
    ('MA', 'Tangier'): (35.7595, -5.834),
    ('MH', 'Majuro'): (7.0897, 171.3803),
    ('MT', 'Valletta'): (35.8989, 14.5146),
    ('MT', 'Sliema'): (35.9122, 14.5042),
    ('MT', 'St Julians'): (35.9182, 14.4898),
    ('MW', 'Lilongwe'): (-13.9626, 33.7741),
    ('MW', 'Blantyre'): (-15.7861, 35.0058),
    ('MX', 'Mexico City'): (19.4326, -99.1332),
    ('MX', 'Guadalajara'): (20.6597, -103.3496),
    ('MX', 'Monterrey'): (25.6866, -100.3161),
    ('MX', 'Cancun'): (21.1619, -86.8515),
    ('MX', 'Tijuana'): (32.5149, -117.0382),
    ('MY', 'Kuala Lumpur'): (3.139, 101.6869),
    ('MY', 'Penang'): (5.4164, 100.3327),
    ('MY', 'Johor Bahru'): (1.4927, 103.7414),
    ('MY', 'Kota Kinabalu'): (5.9804, 116.0735),
    ('NA', 'Windhoek'): (-22.5609, 17.0658),
    ('NA', 'Swakopmund'): (-22.6783, 14.5266),
    ('NG', 'Lagos'): (6.5244, 3.3792),
    ('NG', 'Abuja'): (9.0765, 7.3986),
    ('NG', 'Port Harcourt'): (4.8156, 7.0498),
    ('NG', 'Ibadan'): (7.3775, 3.947),
    ('NG', 'Kano'): (12.0022, 8.592),
    ('NO', 'Oslo'): (59.9139, 10.7522),
    ('NO', 'Bergen'): (60.3913, 5.3221),
    ('NO', 'Trondheim'): (63.4305, 10.3951),
    ('NR', 'Yaren'): (-0.5477, 166.9209),
    ('PG', 'Port Moresby'): (-9.4438, 147.1803),
    ('PG', 'Lae'): (-6.722, 146.9847),
    ('PK', 'Karachi'): (24.8607, 67.0011),
    ('PK', 'Lahore'): (31.5204, 74.3587),
    ('PK', 'Islamabad'): (33.6844, 73.0479),
    ('PK', 'Rawalpindi'): (33.5651, 73.0169),
    ('PL', 'Warsaw'): (52.2297, 21.0122),
    ('PL', 'Krakow'): (50.0647, 19.945),
    ('PL', 'Gdansk'): (54.352, 18.6466),
    ('PL', 'Wroclaw'): (51.1079, 17.0385),
    ('PT', 'Lisbon'): (38.7223, -9.1393),
    ('PT', 'Porto'): (41.1579, -8.6291),
    ('PT', 'Faro'): (37.0194, -7.9322),
    ('PW', 'Ngerulmud'): (7.5004, 134.6243),
    ('PW', 'Koror'): (7.3419, 134.477),
    ('QA', 'Doha'): (25.2854, 51.531),
    ('QA', 'Al Rayyan'): (25.2919, 51.4244),
    ('RW', 'Kigali'): (-1.9441, 30.0619),
    ('RW', 'Butare'): (-2.5967, 29.7394),
    ('SB', 'Honiara'): (-9.4456, 159.9729),
    ('SE', 'Stockholm'): (59.3293, 18.0686),
    ('SE', 'Gothenburg'): (57.7089, 11.9746),
    ('SE', 'Malmo'): (55.605, 13.0038),
    ('SG', 'Singapore'): (1.3521, 103.8198),
    ('SI', 'Ljubljana'): (46.0569, 14.5058),
    ('SI', 'Maribor'): (46.5547, 15.6459),
    ('SK', 'Bratislava'): (48.1486, 17.1077),
    ('SK', 'Kosice'): (48.7164, 21.2611),
    ('SL', 'Freetown'): (8.4657, -13.2317),
    ('SS', 'Juba'): (4.8594, 31.5713),
    ('SZ', 'Mbabane'): (-26.3054, 31.1367),
    ('SZ', 'Manzini'): (-26.498, 31.38),
    ('TN', 'Tunis'): (36.8065, 10.1815),
    ('TN', 'Sfax'): (34.7398, 10.76),
    ('TN', 'Sousse'): (35.8245, 10.6346),
    ('TO', 'Nukualofa'): (-21.1394, -175.2018),
    ('TR', 'Istanbul'): (41.0082, 28.9784),
    ('TR', 'Ankara'): (39.9334, 32.8597),
    ('TR', 'Izmir'): (38.4237, 27.1428),
    ('TR', 'Antalya'): (36.8969, 30.7133),
    ('TT', 'Port Of Spain'): (10.6596, -61.5086),
    ('TT', 'San Fernando'): (10.2833, -61.4667),
    ('TT', 'Chaguanas'): (10.5167, -61.4167),
    ('TV', 'Funafuti'): (-8.5243, 179.1942),
    ('UG', 'Kampala'): (0.3476, 32.5825),
    ('UG', 'Entebbe'): (0.0512, 32.4637),
    ('UG', 'Jinja'): (0.4244, 33.2041),
    ('VC', 'Kingstown'): (13.16, -61.2248),
    ('VN', 'Ho Chi Minh City'): (10.8231, 106.6297),
    ('VN', 'Hanoi'): (21.0278, 105.8342),
    ('VN', 'Da Nang'): (16.0544, 108.2022),
    ('VN', 'Nha Trang'): (12.2388, 109.1967),
    ('VU', 'Port Vila'): (-17.7333, 168.3273),
    ('WS', 'Apia'): (-13.8333, -171.7667),
    ('ZA', 'Cape Town'): (-33.9249, 18.4241),
    ('ZA', 'Johannesburg'): (-26.2041, 28.0473),
    ('ZA', 'Durban'): (-29.8587, 31.0218),
    ('ZA', 'Pretoria'): (-25.7479, 28.2293),
    ('ZA', 'Port Elizabeth'): (-33.9608, 25.6022),
    ('ZM', 'Lusaka'): (-15.3875, 28.3228),
    ('ZM', 'Ndola'): (-12.9587, 28.6366),
    ('ZM', 'Kitwe'): (-12.8024, 28.2132),
    ('ZW', 'Harare'): (-17.8252, 31.0335),
    ('ZW', 'Bulawayo'): (-20.1486, 28.5806),
}

COUNTRY_TIMEZONES: dict[str, str] = {
    'GB': 'Europe/London',
    'IE': 'Europe/Dublin',
    'US': 'America/New_York',
    'CA': 'America/Toronto',
    'AU': 'Australia/Sydney',
    'NZ': 'Pacific/Auckland',
    'PH': 'Asia/Manila',
    'TH': 'Asia/Bangkok',
    'NL': 'Europe/Amsterdam',
    'BS': 'America/Nassau',
    'JM': 'America/Jamaica',
    'AE': 'Asia/Dubai',
    'AG': 'America/Antigua',
    'AR': 'America/Argentina/Buenos_Aires',
    'AT': 'Europe/Vienna',
    'BB': 'America/Barbados',
    'BE': 'Europe/Brussels',
    'BR': 'America/Sao_Paulo',
    'BW': 'Africa/Gaborone',
    'BZ': 'America/Belize',
    'CH': 'Europe/Zurich',
    'CL': 'America/Santiago',
    'CM': 'Africa/Douala',
    'CN': 'Asia/Shanghai',
    'CO': 'America/Bogota',
    'CZ': 'Europe/Prague',
    'DE': 'Europe/Berlin',
    'DK': 'Europe/Copenhagen',
    'EG': 'Africa/Cairo',
    'ES': 'Europe/Madrid',
    'FI': 'Europe/Helsinki',
    'FJ': 'Pacific/Fiji',
    'FM': 'Pacific/Pohnpei',
    'FR': 'Europe/Paris',
    'GD': 'America/Grenada',
    'GH': 'Africa/Accra',
    'GM': 'Africa/Banjul',
    'GR': 'Europe/Athens',
    'GY': 'America/Guyana',
    'HR': 'Europe/Zagreb',
    'ID': 'Asia/Jakarta',
    'IL': 'Asia/Jerusalem',
    'IN': 'Asia/Kolkata',
    'IS': 'Atlantic/Reykjavik',
    'IT': 'Europe/Rome',
    'JO': 'Asia/Amman',
    'JP': 'Asia/Tokyo',
    'KE': 'Africa/Nairobi',
    'KI': 'Pacific/Tarawa',
    'KN': 'America/St_Kitts',
    'KR': 'Asia/Seoul',
    'LR': 'Africa/Monrovia',
    'LS': 'Africa/Maseru',
    'MA': 'Africa/Casablanca',
    'MH': 'Pacific/Majuro',
    'MT': 'Europe/Malta',
    'MW': 'Africa/Blantyre',
    'MX': 'America/Mexico_City',
    'MY': 'Asia/Kuala_Lumpur',
    'NA': 'Africa/Windhoek',
    'NG': 'Africa/Lagos',
    'NO': 'Europe/Oslo',
    'NR': 'Pacific/Nauru',
    'PG': 'Pacific/Port_Moresby',
    'PK': 'Asia/Karachi',
    'PL': 'Europe/Warsaw',
    'PT': 'Europe/Lisbon',
    'PW': 'Pacific/Palau',
    'QA': 'Asia/Qatar',
    'RW': 'Africa/Kigali',
    'SB': 'Pacific/Guadalcanal',
    'SE': 'Europe/Stockholm',
    'SG': 'Asia/Singapore',
    'SI': 'Europe/Ljubljana',
    'SK': 'Europe/Bratislava',
    'SL': 'Africa/Freetown',
    'SS': 'Africa/Juba',
    'SZ': 'Africa/Mbabane',
    'TN': 'Africa/Tunis',
    'TO': 'Pacific/Tongatapu',
    'TR': 'Europe/Istanbul',
    'TT': 'America/Port_of_Spain',
    'TV': 'Pacific/Funafuti',
    'UG': 'Africa/Kampala',
    'VC': 'America/St_Vincent',
    'VN': 'Asia/Ho_Chi_Minh',
    'VU': 'Pacific/Efate',
    'WS': 'Pacific/Apia',
    'ZA': 'Africa/Johannesburg',
    'ZM': 'Africa/Lusaka',
    'ZW': 'Africa/Harare',
}

TARGET_MARKETS: list[str] = ['GB', 'US', 'CA', 'AU', 'IE', 'NZ', 'PH', 'TH', 'NL', 'BS', 'JM', 'AE', 'AG', 'AR', 'AT', 'BB', 'BE', 'BR', 'BW', 'BZ', 'CH', 'CL', 'CM', 'CN', 'CO', 'CZ', 'DE', 'DK', 'EG', 'ES', 'FI', 'FJ', 'FM', 'FR', 'GD', 'GH', 'GM', 'GR', 'GY', 'HR', 'ID', 'IL', 'IN', 'IS', 'IT', 'JO', 'JP', 'KE', 'KI', 'KN', 'KR', 'LR', 'LS', 'MA', 'MH', 'MT', 'MW', 'MX', 'MY', 'NA', 'NG', 'NO', 'NR', 'PG', 'PK', 'PL', 'PT', 'PW', 'QA', 'RW', 'SB', 'SE', 'SG', 'SI', 'SK', 'SL', 'SS', 'SZ', 'TN', 'TO', 'TR', 'TT', 'TV', 'UG', 'VC', 'VN', 'VU', 'WS', 'ZA', 'ZM', 'ZW']

NEW_MARKETS: list[str] = ['AE', 'AG', 'AR', 'AT', 'BB', 'BE', 'BR', 'BW', 'BZ', 'CH', 'CL', 'CM', 'CN', 'CO', 'CZ', 'DE', 'DK', 'EG', 'ES', 'FI', 'FJ', 'FM', 'FR', 'GD', 'GH', 'GM', 'GR', 'GY', 'HR', 'ID', 'IL', 'IN', 'IS', 'IT', 'JO', 'JP', 'KE', 'KI', 'KN', 'KR', 'LR', 'LS', 'MA', 'MH', 'MT', 'MW', 'MX', 'MY', 'NA', 'NG', 'NO', 'NR', 'PG', 'PK', 'PL', 'PT', 'PW', 'QA', 'RW', 'SB', 'SE', 'SG', 'SI', 'SK', 'SL', 'SS', 'SZ', 'TN', 'TO', 'TR', 'TT', 'TV', 'UG', 'VC', 'VN', 'VU', 'WS', 'ZA', 'ZM', 'ZW']

# Append hotels / pubs / bars / cafés / restaurants for every scrape market.
merge_hospitality_into_sources(MARKET_SOURCES, TARGET_MARKETS)

DEFAULT_CITY: dict[str, str] = {code: cities[0] for code, cities in MARKET_CITIES.items()}

COUNTRY_ALIASES: dict[str, str] = {
    'UK': 'GB',
    'EI': 'IE',
    'UAE': 'AE',
    'THAILAND': 'TH',
    'JAMAICA': 'JM',
    'BAHAMAS': 'BS',
    'NETHERLANDS': 'NL',
    'HOLLAND': 'NL',
    'CZECH REPUBLIC': 'CZ',
    'CZECHIA': 'CZ',
    'SOUTH KOREA': 'KR',
    'KOREA': 'KR',
    'VIET NAM': 'VN',
    'U.S.': 'US',
    'USA': 'US',
    'TRINIDAD': 'TT',
    'ANTIGUA': 'AG',
    'ST KITTS': 'KN',
    'SAINT KITTS': 'KN',
    'ST VINCENT': 'VC',
    'MICRONESIA': 'FM',
    'ESWATINI': 'SZ',
    'SWAZILAND': 'SZ',
    'THE GAMBIA': 'GM',
    'GAMBIA': 'GM',
    'PAPUA NEW GUINEA': 'PG',
}

def iter_market_areas(
    country_codes: list[str] | None = None,
) -> list[tuple[str, str]]:
    """Flatten (country, city) pairs for worldwide scraping."""
    codes = country_codes or TARGET_MARKETS
    areas: list[tuple[str, str]] = []
    for code in codes:
        upper = COUNTRY_ALIASES.get(code.strip().upper(), code.strip().upper())
        cities = MARKET_CITIES.get(upper) or [DEFAULT_CITY.get(upper, "Unknown")]
        for city in cities:
            areas.append((upper, city))
    return areas

# Multiply GBP-ish template prices (~7.50) into local currency ballpark.
CURRENCY_PRICE_SCALE: dict[str, float] = {
    'AED': 4.6487,
    'ARS': 1202.5316,
    'AUD': 1.9241,
    'BBD': 2.5316,
    'BRL': 6.9620,
    'BSD': 1.2658,
    'BWP': 17.0886,
    'BZD': 2.5316,
    'CAD': 1.7215,
    'CHF': 1.1139,
    'CLP': 1202.5316,
    'CNY': 9.1772,
    'COP': 5189.8734,
    'CZK': 29.1139,
    'DKK': 8.7342,
    'EGP': 60.7595,
    'EUR': 1.1646,
    'FJD': 2.8481,
    'GBP': 1.0000,
    'GHS': 19.6203,
    'GMD': 84.8101,
    'GYD': 264.5570,
    'IDR': 20253.1646,
    'ILS': 4.6835,
    'INR': 105.0633,
    'ISK': 174.6835,
    'JMD': 196.2025,
    'JOD': 0.8987,
    'JPY': 189.8734,
    'KES': 164.5570,
    'KRW': 1708.8608,
    'LRD': 240.5063,
    'LSL': 23.4177,
    'MAD': 12.6582,
    'MWK': 2189.8734,
    'MXN': 21.7722,
    'MYR': 5.9494,
    'NAD': 23.4177,
    'NGN': 1962.0253,
    'NOK': 13.6709,
    'NZD': 2.0886,
    'PGK': 4.9367,
    'PHP': 70.8861,
    'PKR': 351.8987,
    'PLN': 5.0633,
    'QAR': 4.6076,
    'RWF': 1645.5696,
    'SBD': 10.6329,
    'SEK': 13.2911,
    'SGD': 1.6962,
    'SLE': 28.4810,
    'SSP': 1645.5696,
    'SZL': 23.4177,
    'THB': 44.3038,
    'TND': 3.9241,
    'TOP': 2.9747,
    'TRY': 43.0380,
    'TTD': 8.6076,
    'UGX': 4683.5443,
    'USD': 1.2658,
    'VND': 31645.5696,
    'VUV': 151.8987,
    'WST': 3.4810,
    'XAF': 759.4937,
    'XCD': 3.4177,
    'ZAR': 23.4177,
    'ZMW': 34.1772,
}

