"""Fixture deals for the Weekly Specials preview and tests.

These rows mirror the junk that landed in a Galway subscriber's issue
(slot spam, a parked domain, hotels, zero prices, other countries) plus
a few real Irish dining offers. Nothing here is emailed on its own.
"""

from __future__ import annotations

from datetime import datetime, timezone
from decimal import Decimal

from app.services.weekly_specials import WeeklyDeal


def _at(day: int, hour: int = 12) -> datetime:
    return datetime(2026, 10, day, hour, tzinfo=timezone.utc)


def _deal(
    *,
    deal_id: str,
    title: str,
    merchant: str,
    country: str,
    city: str,
    price: str,
    currency: str,
    when: datetime,
    description: str = "",
    category: str = "restaurants-cafes-bistros",
    outbound: str = "https://merchant.example/menu",
) -> WeeklyDeal:
    return WeeklyDeal(
        id=deal_id,
        title=title,
        description=description,
        merchant_name=merchant,
        venue_category=category,
        country_code=country,
        city=city,
        latitude=None,
        longitude=None,
        deal_price=Decimal(price),
        currency_code=currency,
        created_at=when,
        outbound_url=outbound,
    )


def galway_issue_fixtures() -> list[WeeklyDeal]:
    """Junk from the reported Galway issue, plus Irish offers that should remain."""
    return [
        _deal(
            deal_id="10000000-0000-4000-8000-000000000001",
            title="AKUNBOS: Situs Slot Gacor Hari Ini",
            merchant="Cardo's Steakhouse",
            country="IE",
            city="Galway",
            price="10.00",
            currency="EUR",
            when=_at(8, 9),
            outbound="https://slot-spam.example/gacor",
        ),
        _deal(
            deal_id="10000000-0000-4000-8000-000000000002",
            title="AKUNBOS: Situs Slot Gacor Hari Ini",
            merchant="Cardo's Steakhouse",
            country="IE",
            city="Galway",
            price="10.00",
            currency="EUR",
            when=_at(8, 8),
            outbound="https://slot-spam.example/gacor-2",
        ),
        _deal(
            deal_id="10000000-0000-4000-8000-000000000003",
            title="Parked Domain name on Hostinger",
            merchant="Parked Domain",
            country="IE",
            city="Galway",
            price="5.00",
            currency="EUR",
            when=_at(8, 7),
            outbound="https://parked.example/",
        ),
        _deal(
            deal_id="10000000-0000-4000-8000-000000000004",
            title="Hotel Details",
            merchant="Aiden",
            country="IE",
            city="Galway",
            price="0.00",
            currency="EUR",
            when=_at(8, 6),
            category="hotels-resorts-bbs",
            outbound="https://aiden-hotel.example/details",
        ),
        _deal(
            deal_id="10000000-0000-4000-8000-000000000005",
            title="Overview & Booking",
            merchant="Sea Breeze Guest House",
            country="IE",
            city="Galway",
            price="90.00",
            currency="EUR",
            when=_at(8, 5),
            category="hotels-resorts-bbs",
            outbound="https://seabreeze.example/booking",
        ),
        _deal(
            deal_id="10000000-0000-4000-8000-000000000018",
            title="Deluxe room package",
            merchant="The g Hotel",
            country="IE",
            city="Galway",
            price="140.00",
            currency="EUR",
            when=_at(8, 2),
            category="hotels-resorts-bbs",
            outbound="https://theghotel.example/rooms",
        ),
        _deal(
            deal_id="10000000-0000-4000-8000-000000000006",
            title="Cardo's Steakhouse",
            merchant="Cardo's Steakhouse",
            country="IE",
            city="Galway",
            price="25.00",
            currency="EUR",
            when=_at(8, 4),
            outbound="https://cardos.example/",
        ),
        _deal(
            deal_id="10000000-0000-4000-8000-000000000007",
            title="Steak night",
            merchant="The Skeff",
            country="IE",
            city="Galway",
            price="0.00",
            currency="EUR",
            when=_at(8, 3),
            outbound="https://theskeff.example/steak",
        ),
        _deal(
            deal_id="10000000-0000-4000-8000-000000000008",
            title="Legoland Hotel Dubai",
            merchant="Legoland Hotel Dubai",
            country="AE",
            city="Dubai",
            price="200.00",
            currency="AED",
            when=_at(9, 18),
            category="hotels-resorts-bbs",
            outbound="https://legoland-hotel.example/",
        ),
        _deal(
            deal_id="10000000-0000-4000-8000-000000000009",
            title="Doha Dynasty Hotel",
            merchant="Doha Dynasty Hotel",
            country="QA",
            city="Doha",
            price="0.00",
            currency="QAR",
            when=_at(9, 17),
            category="hotels-resorts-bbs",
            outbound="https://doha-dynasty.example/",
        ),
        _deal(
            deal_id="10000000-0000-4000-8000-000000000010",
            title="Lunch set",
            merchant="Seoul BBQ",
            country="KR",
            city="Seoul",
            price="15000",
            currency="KRW",
            when=_at(9, 16),
            outbound="https://seoul-bbq.example/",
        ),
        _deal(
            deal_id="10000000-0000-4000-8000-000000000011",
            title="Set menu",
            merchant="Warsaw Pierogi",
            country="PL",
            city="Warsaw",
            price="40.00",
            currency="PLN",
            when=_at(9, 15),
            outbound="https://warsaw-pierogi.example/",
        ),
        _deal(
            deal_id="10000000-0000-4000-8000-000000000012",
            title="Brunch special",
            merchant="Auckland Cafe",
            country="NZ",
            city="Auckland",
            price="18.00",
            currency="NZD",
            when=_at(9, 14),
            outbound="https://auckland-cafe.example/",
        ),
        _deal(
            deal_id="10000000-0000-4000-8000-000000000013",
            title="Wine tasting",
            merchant="Cape Town Cellar",
            country="ZA",
            city="Cape Town",
            price="100.00",
            currency="ZAR",
            when=_at(9, 13),
            outbound="https://cape-town-cellar.example/",
        ),
        _deal(
            deal_id="10000000-0000-4000-8000-000000000014",
            title="Breakfast bundle",
            merchant="Sydney Diner",
            country="AU",
            city="Sydney",
            price="15.00",
            currency="AUD",
            when=_at(9, 12),
            outbound="https://sydney-diner.example/",
        ),
        _deal(
            deal_id="10000000-0000-4000-8000-000000000015",
            title="Island platter",
            merchant="Suva Grill",
            country="FJ",
            city="Suva",
            price="0.00",
            currency="FJD",
            when=_at(9, 11),
            outbound="https://suva-grill.example/",
        ),
        _deal(
            deal_id="10000000-0000-4000-8000-000000000016",
            title="River special",
            merchant="Georgetown Kitchen",
            country="GY",
            city="Georgetown",
            price="0.00",
            currency="GYD",
            when=_at(9, 10),
            outbound="https://georgetown-kitchen.example/",
        ),
        _deal(
            deal_id="20000000-0000-4000-8000-000000000001",
            title="Early-bird set menu",
            merchant="Ard Bia",
            country="IE",
            city="Galway",
            price="22.00",
            currency="EUR",
            when=_at(8, 18),
            outbound="https://ardbia.example/menu",
        ),
        _deal(
            deal_id="20000000-0000-4000-8000-000000000002",
            title="Weekday lunch special",
            merchant="Kai Cafe",
            country="IE",
            city="Galway",
            price="14.50",
            currency="EUR",
            when=_at(7, 12),
            outbound="https://kaicafe.example/lunch",
        ),
        _deal(
            deal_id="20000000-0000-4000-8000-000000000003",
            title="Weekday lunch special",
            merchant="Kai Cafe",
            country="IE",
            city="Galway",
            price="14.50",
            currency="EUR",
            when=_at(6, 12),
            outbound="https://kaicafe.example/lunch-copy",
        ),
        _deal(
            deal_id="20000000-0000-4000-8000-000000000004",
            title="Weekday lunch special",
            merchant="Kai Cafe",
            country="IE",
            city="Cork",
            price="14.50",
            currency="EUR",
            when=_at(9, 20),
            outbound="https://kaicafe.example/cork",
        ),
        _deal(
            deal_id="20000000-0000-4000-8000-000000000005",
            title="Sunday carvery lunch",
            merchant="Galway Bay Hotel",
            country="IE",
            city="Galway",
            price="16.00",
            currency="EUR",
            when=_at(6, 15),
            category="hotels-resorts-bbs",
            description="Carvery lunch in the hotel restaurant.",
            outbound="https://galwaybayhotel.example/carvery",
        ),
        _deal(
            deal_id="20000000-0000-4000-8000-000000000006",
            title="Burger and a pint",
            merchant="The Quays Bar",
            country="IE",
            city="Galway",
            price="12.00",
            currency="USD",
            when=_at(5, 18),
            category="clubs-bars-pubs",
            outbound="https://thequays.example/burger",
        ),
        _deal(
            deal_id="20000000-0000-4000-8000-000000000007",
            title="20% off fish and chips",
            merchant="McDonagh's",
            country="IE",
            city="Galway",
            price="0.00",
            currency="EUR",
            when=_at(4, 12),
            outbound="https://mcdonaghs.example/fish",
        ),
        _deal(
            deal_id="20000000-0000-4000-8000-000000000008",
            title="Free kids ice cream with any main",
            merchant="Murphy's Ice Cream",
            country="IE",
            city="Galway",
            price="0.00",
            currency="EUR",
            when=_at(3, 12),
            outbound="https://murphys.example/ice-cream",
        ),
        _deal(
            deal_id="20000000-0000-4000-8000-000000000009",
            title="Happy hour pints",
            merchant="The Locke",
            country="IE",
            city="Limerick",
            price="8.00",
            currency="EUR",
            when=_at(9, 21),
            category="clubs-bars-pubs",
            outbound="https://thelocke.example/happy-hour",
        ),
        _deal(
            deal_id="20000000-0000-4000-8000-000000000010",
            title="Lunch deal",
            merchant="Farmgate Cafe",
            country="IE",
            city="Cork",
            price="13.00",
            currency="EUR",
            when=_at(9, 19),
            outbound="https://farmgate.example/lunch",
        ),
        _deal(
            deal_id="20000000-0000-4000-8000-000000000011",
            title="Weekend brunch",
            merchant="Brother Hubbard",
            country="IE",
            city="Dublin",
            price="15.00",
            currency="EUR",
            when=_at(9, 22),
            outbound="https://brotherhubbard.example/brunch",
        ),
    ]
