# Generated by Django 3.1.7 on 2021-03-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
