# Generated by Django 3.1.7 on 2021-03-21 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptier',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membershiptier',
            name='image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='images/products'),
            preserve_default=False,
        ),
    ]
