# Generated by Django 3.1.7 on 2021-03-04 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deals_display', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='rating',
        ),
        migrations.AddField(
            model_name='deal',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='restaurant_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
