# Generated by Django 3.1.7 on 2021-03-21 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210321_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='phone_num',
            field=models.PositiveIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deal',
            name='address',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='deal',
            name='website_address',
            field=models.CharField(max_length=254),
        ),
    ]
