# Generated by Django 3.1.7 on 2021-03-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210321_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='phone_num',
            field=models.CharField(max_length=24),
        ),
    ]
