# Generated by Django 3.1.7 on 2021-03-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210321_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='phone_num',
            new_name='phone_number',
        ),
    ]
