# Generated by Django 3.1.7 on 2021-03-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210321_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='phone_number',
        ),
    ]
