# Generated by Django 3.1.7 on 2021-03-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_deal_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='phone_num',
            field=models.PositiveIntegerField(default='12345'),
        ),
    ]
