# Generated by Django 3.1.7 on 2021-03-21 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_deal_phone_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='phone_num',
        ),
        migrations.AddField(
            model_name='deal',
            name='number_phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=48),
            preserve_default=False,
        ),
    ]
