# Generated by Django 3.1.7 on 2021-03-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210321_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=models.TextField(max_length=2054),
        ),
    ]
