# Generated by Django 3.1.7 on 2021-03-26 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='deal_name',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='Serves',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='valid',
        ),
        migrations.AddField(
            model_name='deal',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='number_phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=48),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='price',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='restaurant_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='website_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=models.TextField(max_length=2054),
        ),
    ]
